import { useState, useEffect, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import axios from 'axios'
import MapView from '../components/MapView'
import { QRCodeSVG } from 'qrcode.react'
import { formatDateTime } from '../utils/dateFormatter'

const Devices = () => {
  const navigate = useNavigate()
  const [devices, setDevices] = useState([])
  const [loading, setLoading] = useState(true)
  const [viewMode, setViewMode] = useState('list') // 'list' or 'grid'
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedDevices, setSelectedDevices] = useState([])
  const [sortConfig, setSortConfig] = useState({ key: null, direction: 'asc' })
  const [filters, setFilters] = useState({
    labels: [],
    attributes: [],
    smartFilters: []
  })
  const [showFilters, setShowFilters] = useState(true)
  const [showNewDeviceModal, setShowNewDeviceModal] = useState(false)
  const [showQRCodeModal, setShowQRCodeModal] = useState(false)
  const [connectionKey, setConnectionKey] = useState('')
  const [createdDeviceName, setCreatedDeviceName] = useState('')
  const [newDevice, setNewDevice] = useState({
    name: '',
    device_id: '',
    device_type: 'laptop',
    connection_key: '' // Generated by backend
  })

  useEffect(() => {
    fetchDevices()
  }, [])

  const fetchDevices = async () => {
    try {
      const token = localStorage.getItem('token')
      if (!token) {
        console.error('No authentication token found')
        setLoading(false)
        return
      }
      
      console.log('Fetching devices from API...')
      // Add cache-busting timestamp to ensure fresh data
      const response = await axios.get(`http://localhost:5000/api/get_devices?t=${Date.now()}`, {
        headers: { Authorization: `Bearer ${token}` }
      })
      
      console.log('API Response:', response.data)
      const devicesList = response.data.devices || []
      console.log(`Loaded ${devicesList.length} device(s)`)
      
      // Log coordinates for debugging
      devicesList.forEach(device => {
        if (device.last_lat && device.last_lng) {
          console.log(`[Devices] Device ${device.name} coordinates: lat=${device.last_lat}, lng=${device.last_lng}`)
        }
      })
      
      setDevices(devicesList)
    } catch (error) {
      console.error('Error fetching devices:', error)
      if (error.response) {
        console.error('Response status:', error.response.status)
        console.error('Response data:', error.response.data)
        if (error.response.status === 401) {
          alert('Session expired. Please log in again.')
        }
      }
      setDevices([]) // Set empty array on error
    } finally {
      setLoading(false)
    }
  }

  // Get unique labels from devices
  const availableLabels = useMemo(() => {
    const labels = new Set()
    devices.forEach(device => {
      if (device.device_type) labels.add(device.device_type)
    })
    return Array.from(labels)
  }, [devices])

  // Get device attributes
  const deviceAttributes = useMemo(() => {
    const attrs = {
      'CLIENT': new Set(),
      'CPU MODEL': new Set(),
      'PROCESSOR SPEED': new Set(),
      'OS': new Set(),
      'RAM SIZE': new Set(),
      'STATUS': new Set(),
      'DEVICE TYPE': new Set()
    }
    
    devices.forEach(device => {
      attrs['CLIENT'].add(device.device_id || 'Unknown')
      attrs['OS'].add(device.device_type || 'Unknown')
      attrs['STATUS'].add(device.status || 'Unknown')
      attrs['DEVICE TYPE'].add(device.device_type || 'Unknown')
    })
    
    return Object.keys(attrs).map(key => ({
      name: key,
      count: attrs[key].size
    }))
  }, [devices])

  // Filter and sort devices
  const filteredDevices = useMemo(() => {
    let filtered = [...devices]

    // Search filter
    if (searchQuery) {
      const query = searchQuery.toLowerCase()
      filtered = filtered.filter(device =>
        device.name?.toLowerCase().includes(query) ||
        device.device_id?.toLowerCase().includes(query) ||
        device.device_type?.toLowerCase().includes(query) ||
        device.status?.toLowerCase().includes(query)
      )
    }

    // Label filters
    if (filters.labels.length > 0) {
      filtered = filtered.filter(device =>
        filters.labels.some(label => device.device_type === label)
      )
    }

    // Smart filters
    filters.smartFilters.forEach(filter => {
      switch (filter) {
        case 'Missing':
          filtered = filtered.filter(d => d.is_missing)
          break
        case 'Not Missing':
          filtered = filtered.filter(d => !d.is_missing)
          break
        case 'Connected':
          filtered = filtered.filter(d => {
            const lastSeen = new Date(d.last_seen)
            const now = new Date()
            const diffHours = (now - lastSeen) / (1000 * 60 * 60)
            return diffHours < 24
          })
          break
        case 'Disconnected':
          filtered = filtered.filter(d => {
            const lastSeen = new Date(d.last_seen)
            const now = new Date()
            const diffHours = (now - lastSeen) / (1000 * 60 * 60)
            return diffHours >= 24
          })
          break
        case 'Seen in the last 24 hours':
          filtered = filtered.filter(d => {
            const lastSeen = new Date(d.last_seen)
            const now = new Date()
            const diffHours = (now - lastSeen) / (1000 * 60 * 60)
            return diffHours < 24
          })
          break
        case 'Seen in the last 7 days':
          filtered = filtered.filter(d => {
            const lastSeen = new Date(d.last_seen)
            const now = new Date()
            const diffDays = (now - lastSeen) / (1000 * 60 * 60 * 24)
            return diffDays < 7
          })
          break
        case 'Seen in the last 30 days':
          filtered = filtered.filter(d => {
            const lastSeen = new Date(d.last_seen)
            const now = new Date()
            const diffDays = (now - lastSeen) / (1000 * 60 * 60 * 24)
            return diffDays < 30
          })
          break
      }
    })

    // Sorting
    if (sortConfig.key) {
      filtered.sort((a, b) => {
        let aVal = a[sortConfig.key]
        let bVal = b[sortConfig.key]

        if (sortConfig.key === 'last_seen' || sortConfig.key === 'created_at' || sortConfig.key === 'missing_since') {
          aVal = new Date(aVal || 0)
          bVal = new Date(bVal || 0)
        }

        if (typeof aVal === 'string') {
          aVal = aVal.toLowerCase()
          bVal = bVal.toLowerCase()
        }

        if (aVal < bVal) return sortConfig.direction === 'asc' ? -1 : 1
        if (aVal > bVal) return sortConfig.direction === 'asc' ? 1 : -1
        return 0
      })
    }

    return filtered
  }, [devices, searchQuery, filters, sortConfig])

  const handleSort = (key) => {
    setSortConfig(prevConfig => ({
      key,
      direction: prevConfig.key === key && prevConfig.direction === 'asc' ? 'desc' : 'asc'
    }))
  }

  const toggleLabelFilter = (label) => {
    setFilters(prev => ({
      ...prev,
      labels: prev.labels.includes(label)
        ? prev.labels.filter(l => l !== label)
        : [...prev.labels, label]
    }))
  }

  const toggleSmartFilter = (filter) => {
    setFilters(prev => ({
      ...prev,
      smartFilters: prev.smartFilters.includes(filter)
        ? prev.smartFilters.filter(f => f !== filter)
        : [...prev.smartFilters, filter]
    }))
  }

  const removeFilter = (type, value) => {
    setFilters(prev => ({
      ...prev,
      [type]: prev[type].filter(v => v !== value)
    }))
  }

  const handleSelectAll = () => {
    if (selectedDevices.length === filteredDevices.length) {
      setSelectedDevices([])
    } else {
      setSelectedDevices(filteredDevices.map(d => d.id))
    }
  }

  const toggleDeviceSelection = (deviceId) => {
    setSelectedDevices(prev =>
      prev.includes(deviceId)
        ? prev.filter(id => id !== deviceId)
        : [...prev, deviceId]
    )
  }

  const exportToCSV = () => {
    const headers = ['Name', 'Device ID', 'Device Type', 'Status', 'Last Seen', 'Location', 'Created At']
    const rows = filteredDevices.map(device => [
      device.name || '',
      device.device_id || '',
      device.device_type || '',
      device.status || '',
      device.last_seen ? formatDateTime(device.last_seen) : 'N/A',
      device.last_lat && device.last_lng ? `${device.last_lat}, ${device.last_lng}` : 'N/A',
      device.created_at ? formatDateTime(device.created_at) : 'N/A'
    ])

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv' })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `devices-${new Date().toISOString().split('T')[0]}.csv`
    a.click()
    window.URL.revokeObjectURL(url)
  }

  const getStatusDot = (device) => {
    if (device.is_missing) return 'bg-red-500'
    if (device.status === 'active') {
      const lastSeen = new Date(device.last_seen)
      const now = new Date()
      const diffHours = (now - lastSeen) / (1000 * 60 * 60)
      return diffHours < 24 ? 'bg-green-500' : 'bg-yellow-500'
    }
    return 'bg-gray-500'
  }

  const getDeviceIcon = (deviceType) => {
    const type = (deviceType || '').toLowerCase()
    if (type.includes('iphone') || type.includes('ios')) return '📱'
    if (type.includes('phone') || type.includes('mobile')) return '📱'
    if (type.includes('laptop')) return '💻'
    if (type.includes('tablet')) return '📲'
    if (type.includes('desktop')) return '🖥️'
    return '💻'
  }

  const formatLastSeen = (dateString) => {
    if (!dateString) return 'n/a'
    const date = new Date(dateString)
    const now = new Date()
    const diffMs = now - date
    const diffMins = Math.floor(diffMs / (1000 * 60))
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60))
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))

    if (diffMins < 1) return 'Just now'
    if (diffMins < 60) return `${diffMins} minutes ago`
    if (diffHours < 24) return `${diffHours} hours ago`
    if (diffDays < 7) return `${diffDays} days ago`
    return date.toLocaleDateString() + ' - ' + date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  }

  const activeFiltersCount = filters.labels.length + filters.smartFilters.length

  if (loading) {
    return <div className="text-center py-8">Loading devices...</div>
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-white rounded-lg shadow-sm p-4">
        <div className="flex items-center justify-between mb-4">
          <div className="flex-1 max-w-md">
            <input
              type="text"
              placeholder="Filter by name, ID, type..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>
          <div className="flex items-center space-x-3">
            <div className="flex items-center space-x-2 bg-gray-100 rounded-lg p-1">
              <button
                onClick={() => setViewMode('grid')}
                className={`px-3 py-1 rounded ${viewMode === 'grid' ? 'bg-white shadow-sm' : ''}`}
              >
                ⊞
              </button>
              <button
                onClick={() => setViewMode('list')}
                className={`px-3 py-1 rounded ${viewMode === 'list' ? 'bg-white shadow-sm' : ''}`}
              >
                ☰
              </button>
              <button
                onClick={() => setShowFilters(!showFilters)}
                className={`px-3 py-1 rounded ${showFilters ? 'bg-white shadow-sm' : ''}`}
              >
                🌐
              </button>
            </div>
            <button
              onClick={exportToCSV}
              className="px-4 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors"
            >
              EXPORT CSV
            </button>
            <button
              onClick={() => setShowNewDeviceModal(true)}
              className="px-4 py-2 bg-green-500 hover:bg-green-600 text-white rounded-lg transition-colors font-medium"
            >
              + NEW DEVICE
            </button>
          </div>
        </div>

        <div className="text-sm text-gray-600">
          SHOWING {filteredDevices.length} / {devices.length} DEVICES
        </div>
      </div>

      <div className="flex gap-4">
        {/* Filters Sidebar */}
        {showFilters && (
          <div className="w-64 bg-white rounded-lg shadow-sm p-4 h-fit">
            <div className="mb-4">
              <h3 className="font-semibold text-gray-700 mb-2">
                Selected Filters ({activeFiltersCount})
              </h3>
              {activeFiltersCount === 0 && (
                <p className="text-sm text-gray-500">No filters applied</p>
              )}
              {filters.labels.map(label => (
                <span
                  key={label}
                  className="inline-flex items-center px-2 py-1 m-1 bg-blue-100 text-blue-800 rounded text-xs"
                >
                  {label}
                  <button
                    onClick={() => removeFilter('labels', label)}
                    className="ml-1 hover:text-blue-900"
                  >
                    ×
                  </button>
                </span>
              ))}
              {filters.smartFilters.map(filter => (
                <span
                  key={filter}
                  className="inline-flex items-center px-2 py-1 m-1 bg-blue-100 text-blue-800 rounded text-xs"
                >
                  {filter}
                  <button
                    onClick={() => removeFilter('smartFilters', filter)}
                    className="ml-1 hover:text-blue-900"
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>

            <div className="mb-4">
              <div className="flex items-center justify-between mb-2">
                <h4 className="font-medium text-gray-700">Labels</h4>
                <button className="text-xs text-gray-500 hover:text-gray-700">HIDE</button>
              </div>
              <div className="space-y-1">
                {availableLabels.map(label => {
                  const count = devices.filter(d => d.device_type === label).length
                  const isActive = filters.labels.includes(label)
                  return (
                    <button
                      key={label}
                      onClick={() => toggleLabelFilter(label)}
                      className={`w-full text-left px-2 py-1 rounded text-sm flex items-center justify-between ${
                        isActive ? 'bg-blue-50 text-blue-700' : 'hover:bg-gray-50'
                      }`}
                    >
                      <span>[{count}] {label}</span>
                      {isActive && <span className="text-blue-700">×</span>}
                    </button>
                  )
                })}
              </div>
            </div>

            <div className="mb-4">
              <h4 className="font-medium text-gray-700 mb-2">Device Attributes</h4>
              <div className="space-y-1">
                {deviceAttributes.map(attr => (
                  <button
                    key={attr.name}
                    className="w-full text-left px-2 py-1 rounded text-sm hover:bg-gray-50"
                  >
                    [{attr.count}] - {attr.name}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <h4 className="font-medium text-gray-700 mb-2">Smart Filters</h4>
              <div className="space-y-1">
                {['Not Missing', 'Missing', 'Connected', 'Disconnected', 'Seen in the last 24 hours', 'Seen in the last 7 days', 'Seen in the last 30 days'].map(filter => {
                  const isActive = filters.smartFilters.includes(filter)
                  return (
                    <button
                      key={filter}
                      onClick={() => toggleSmartFilter(filter)}
                      className={`w-full text-left px-2 py-1 rounded text-sm ${
                        isActive ? 'bg-blue-50 text-blue-700 font-medium' : 'hover:bg-gray-50'
                      }`}
                    >
                      {filter}
                    </button>
                  )
                })}
              </div>
            </div>
          </div>
        )}

        {/* Main Content */}
        <div className="flex-1">
          {viewMode === 'list' ? (
            <div className="bg-white rounded-lg shadow-sm overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-blue-600 text-white">
                    <tr>
                      <th className="px-4 py-3 text-left">
                        <input
                          type="checkbox"
                          checked={selectedDevices.length === filteredDevices.length && filteredDevices.length > 0}
                          onChange={handleSelectAll}
                          className="rounded"
                        />
                      </th>
                      <th
                        className="px-4 py-3 text-left cursor-pointer hover:bg-blue-700"
                        onClick={() => handleSort('name')}
                      >
                        NAME {sortConfig.key === 'name' && (sortConfig.direction === 'asc' ? '↑' : '↓')}
                      </th>
                      <th
                        className="px-4 py-3 text-left cursor-pointer hover:bg-blue-700"
                        onClick={() => handleSort('device_type')}
                      >
                        OS {sortConfig.key === 'device_type' && (sortConfig.direction === 'asc' ? '↑' : '↓')}
                      </th>
                      <th className="px-4 py-3 text-left">DEVICE ID</th>
                      <th
                        className="px-4 py-3 text-left cursor-pointer hover:bg-blue-700"
                        onClick={() => handleSort('created_at')}
                      >
                        CREATED AT {sortConfig.key === 'created_at' && (sortConfig.direction === 'asc' ? '↑' : '↓')}
                      </th>
                      <th className="px-4 py-3 text-left">STATUS</th>
                      <th
                        className="px-4 py-3 text-left cursor-pointer hover:bg-blue-700"
                        onClick={() => handleSort('last_seen')}
                      >
                        LAST SEEN {sortConfig.key === 'last_seen' && (sortConfig.direction === 'asc' ? '↑' : '↓')}
                      </th>
                      <th className="px-4 py-3 text-left">ACTIONS</th>
                    </tr>
                  </thead>
                  <tbody>
                    {loading ? (
                      <tr>
                        <td colSpan="8" className="px-4 py-8 text-center text-gray-500">
                          <div className="flex items-center justify-center space-x-2">
                            <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-blue-600"></div>
                            <span>Loading devices...</span>
                          </div>
                        </td>
                      </tr>
                    ) : filteredDevices.length === 0 && devices.length === 0 ? (
                      <tr>
                        <td colSpan="8" className="px-4 py-8 text-center text-gray-500">
                          <div className="space-y-3">
                            <p className="text-lg font-semibold">No devices registered</p>
                            <p className="text-sm text-gray-400">
                              Register a device by running the device agent on your device
                            </p>
                            <button
                              onClick={() => fetchDevices()}
                              className="mt-4 px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-sm transition-colors"
                            >
                              🔄 Refresh List
                            </button>
                          </div>
                        </td>
                      </tr>
                    ) : filteredDevices.length === 0 ? (
                      <tr>
                        <td colSpan="8" className="px-4 py-8 text-center text-gray-500">
                          <div className="space-y-2">
                            <p>No devices match your current filters</p>
                            <p className="text-sm text-gray-400">
                              Try clearing filters or search query
                            </p>
                            <button
                              onClick={() => {
                                setSearchQuery('')
                                setFilters({ labels: [], attributes: [], smartFilters: [] })
                              }}
                              className="mt-2 px-3 py-1 bg-gray-200 hover:bg-gray-300 text-gray-700 rounded text-xs transition-colors"
                            >
                              Clear All Filters
                            </button>
                          </div>
                        </td>
                      </tr>
                    ) : (
                      filteredDevices.map(device => (
                        <tr key={device.id} className="border-b border-gray-200 hover:bg-gray-50">
                          <td className="px-4 py-3">
                            <input
                              type="checkbox"
                              checked={selectedDevices.includes(device.id)}
                              onChange={() => toggleDeviceSelection(device.id)}
                              className="rounded"
                            />
                          </td>
                          <td className="px-4 py-3">
                            <div 
                              className="flex items-center space-x-2 cursor-pointer hover:text-blue-600"
                              onClick={() => navigate(`/device/${device.device_id}`)}
                            >
                              <div className={`w-3 h-3 rounded-full ${getStatusDot(device)}`}></div>
                              <span className="text-xl">{getDeviceIcon(device.device_type)}</span>
                              <div>
                                <div className="font-medium text-gray-800">{device.name}</div>
                                {device.device_type && (
                                  <div className="text-xs text-gray-500">{device.device_type}</div>
                                )}
                                {device.device_type && (
                                  <span className="inline-block mt-1 px-2 py-0.5 bg-gray-100 text-gray-600 rounded text-xs">
                                    {device.device_type}
                                  </span>
                                )}
                              </div>
                            </div>
                          </td>
                          <td className="px-4 py-3">
                            <div className="flex items-center space-x-2">
                              {(device.os_name || device.os_version || device.os || '').toLowerCase().includes('windows') && '🪟'}
                              {(device.os_name || device.os_version || device.os || '').toLowerCase().includes('mac') && '🍎'}
                              {(device.os_name || device.os_version || device.os || '').toLowerCase().includes('linux') && '🐧'}
                              {(device.os_name || device.os_version || device.os || '').toLowerCase().includes('iphone') || (device.os_name || device.os_version || device.os || '').toLowerCase().includes('ios') && '📱'}
                              <span className="text-sm">{device.os_version || device.os_name || device.os || device.device_type || 'N/A'}</span>
                            </div>
                          </td>
                          <td className="px-4 py-3 text-sm text-gray-600">{device.device_id}</td>
                          <td className="px-4 py-3 text-sm text-gray-600">
                            {device.created_at ? new Date(device.created_at).toLocaleDateString() : 'N/A'}
                          </td>
                          <td className="px-4 py-3">
                            <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                              device.status === 'active' ? 'bg-green-100 text-green-800' :
                              device.is_missing ? 'bg-red-100 text-red-800' :
                              'bg-gray-100 text-gray-800'
                            }`}>
                              {device.is_missing ? 'Missing' : device.status}
                            </span>
                          </td>
                          <td className="px-4 py-3 text-sm text-gray-600">
                            {formatLastSeen(device.last_seen)}
                          </td>
                          <td className="px-4 py-3">
                            <div className="flex space-x-1">
                              {device.device_type !== 'os_device' && (
                                <>
                                  <button
                                    onClick={() => handleAction(device.device_id, 'lock')}
                                    className="px-2 py-1 bg-blue-500 hover:bg-blue-600 text-white rounded text-xs"
                                    title="Lock"
                                  >
                                    🔒
                                  </button>
                                  <button
                                    onClick={() => handleAction(device.device_id, 'alarm')}
                                    className="px-2 py-1 bg-orange-500 hover:bg-orange-600 text-white rounded text-xs"
                                    title="Alarm"
                                  >
                                    🚨
                                  </button>
                                </>
                              )}
                              <button
                                onClick={() => handleMarkMissing(device.device_id)}
                                className="px-2 py-1 bg-red-500 hover:bg-red-600 text-white rounded text-xs"
                                title="Mark Missing"
                              >
                                🚨
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredDevices.map(device => (
                <div 
                  key={device.id} 
                  className="bg-white rounded-lg shadow-md p-4 hover:shadow-lg transition-shadow cursor-pointer"
                  onClick={() => navigate(`/device/${device.device_id}`)}
                >
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center space-x-2">
                      <div className={`w-3 h-3 rounded-full ${getStatusDot(device)}`}></div>
                      <span className="text-2xl">{getDeviceIcon(device.device_type)}</span>
                    </div>
                    <input
                      type="checkbox"
                      checked={selectedDevices.includes(device.id)}
                      onChange={(e) => {
                        e.stopPropagation()
                        toggleDeviceSelection(device.id)
                      }}
                      onClick={(e) => e.stopPropagation()}
                      className="rounded"
                    />
                  </div>
                  <h3 className="font-semibold text-gray-800 mb-1">{device.name}</h3>
                  <p className="text-sm text-gray-500 mb-2">{device.device_type || 'Unknown'}</p>
                  {device.device_type && (
                    <span className="inline-block px-2 py-0.5 bg-gray-100 text-gray-600 rounded text-xs mb-2">
                      {device.device_type}
                    </span>
                  )}
                  <div className="space-y-1 text-sm text-gray-600 mb-3">
                    <div>Status: <span className="font-medium">{device.status}</span></div>
                    <div>Last seen: {formatLastSeen(device.last_seen)}</div>
                    {device.last_lat && device.last_lng && (
                      <div>📍 {device.last_lat.toFixed(4)}, {device.last_lng.toFixed(4)}</div>
                    )}
                  </div>
                  <div className="flex space-x-2" onClick={(e) => e.stopPropagation()}>
                    {device.device_type !== 'os_device' && (
                      <>
                        <button
                          onClick={() => handleAction(device.device_id, 'lock')}
                          className="flex-1 bg-blue-500 hover:bg-blue-600 text-white py-2 px-2 rounded text-xs"
                        >
                          🔒 Lock
                        </button>
                        <button
                          onClick={() => handleAction(device.device_id, 'alarm')}
                          className="flex-1 bg-orange-500 hover:bg-orange-600 text-white py-2 px-2 rounded text-xs"
                        >
                          🚨 Alarm
                        </button>
                      </>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* New Device Modal */}
      {showNewDeviceModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-gray-800">Add New Device</h3>
              <button
                onClick={() => {
                  setShowNewDeviceModal(false)
                  setNewDevice({ name: '', device_id: '', device_type: 'laptop', connection_key: '' })
                }}
                className="text-gray-500 hover:text-gray-700 text-2xl font-bold"
              >
                ×
              </button>
            </div>
            
            <div className="space-y-4">
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="text-sm text-blue-800">
                  <strong>ℹ️ Manual Device Creation:</strong> Create a device entry here, then use the connection key on your physical device to connect to this dashboard.
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Device Name *
                </label>
                <input
                  type="text"
                  value={newDevice.name}
                  onChange={(e) => setNewDevice({ ...newDevice, name: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="e.g., My iPhone, Work Laptop"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Device ID *
                </label>
                <input
                  type="text"
                  value={newDevice.device_id}
                  onChange={(e) => setNewDevice({ ...newDevice, device_id: e.target.value.toLowerCase().replace(/\s+/g, '-') })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="e.g., my-iphone-13, work-laptop-01"
                />
                <p className="text-xs text-gray-500 mt-1">
                  Unique identifier (lowercase, no spaces). This will be used by the device agent to connect.
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Device Type *
                </label>
                <select
                  value={newDevice.device_type}
                  onChange={(e) => setNewDevice({ ...newDevice, device_type: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                >
                  <option value="laptop">💻 Laptop</option>
                  <option value="desktop">🖥️ Desktop</option>
                  <option value="iphone">📱 iPhone</option>
                  <option value="android">📱 Android Phone</option>
                  <option value="tablet">📲 Tablet</option>
                  <option value="other">🔷 Other</option>
                </select>
              </div>

              <div className="border-t pt-4 mt-4">
                <h4 className="font-medium text-gray-700 mb-3">After Creating Device:</h4>
                <ol className="list-decimal list-inside space-y-2 text-sm text-gray-600">
                  <li>Copy the <strong>Connection Key</strong> that will be shown after creation</li>
                  <li>On your physical device, run the registration script with this key:
                    <div className="bg-gray-100 p-2 rounded mt-1 font-mono text-xs">
                      python register_device.py --connect-key YOUR_KEY
                    </div>
                  </li>
                  <li>Or edit the agent config file and add: <code className="bg-gray-100 px-1 rounded">"connection_key": "YOUR_KEY"</code></li>
                </ol>
              </div>
            </div>

            <div className="mt-6 flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowNewDeviceModal(false)
                  setNewDevice({ name: '', device_id: '', device_type: 'laptop', connection_key: '' })
                }}
                className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={async () => {
                  if (!newDevice.name || !newDevice.device_id) {
                    alert('Please fill in Device Name and Device ID')
                    return
                  }
                  
                  try {
                    const token = localStorage.getItem('token')
                    const response = await axios.post(
                      'http://localhost:5000/api/create_device',
                      {
                        name: newDevice.name,
                        device_id: newDevice.device_id,
                        device_type: newDevice.device_type
                      },
                      { headers: { Authorization: `Bearer ${token}` } }
                    )
                    
                    const deviceData = response.data.device
                    const connKey = response.data.connection_key
                    
                    // Show QR code modal instead of alert
                    setConnectionKey(connKey)
                    setCreatedDeviceName(newDevice.name)
                    setShowNewDeviceModal(false)
                    setShowQRCodeModal(true)
                    setNewDevice({ name: '', device_id: '', device_type: 'laptop', connection_key: '' })
                    fetchDevices()
                  } catch (error) {
                    alert(error.response?.data?.error || 'Failed to create device')
                  }
                }}
                className="px-6 py-2 bg-green-500 hover:bg-green-600 text-white rounded-lg transition-colors font-medium"
              >
                Create Device
              </button>
            </div>
          </div>
        </div>
      )}

      {/* QR Code Modal */}
      {showQRCodeModal && connectionKey && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-gray-800">Scan QR Code to Connect</h3>
              <button
                onClick={() => {
                  setShowQRCodeModal(false)
                  setConnectionKey('')
                  setCreatedDeviceName('')
                }}
                className="text-gray-500 hover:text-gray-700 text-2xl font-bold"
              >
                ×
              </button>
            </div>
            
            <div className="text-center space-y-4">
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4">
                <p className="text-sm text-blue-800">
                  <strong>✅ Device "{createdDeviceName}" created!</strong>
                </p>
                <p className="text-xs text-blue-700 mt-2">
                  Scan this QR code with your device to connect automatically.
                </p>
              </div>

              <div className="flex justify-center bg-white p-4 rounded-lg border-2 border-gray-200">
                <QRCodeSVG 
                  value={connectionKey} 
                  size={256}
                  level="H"
                  includeMargin={true}
                />
              </div>

              <div className="space-y-2">
                <p className="text-sm font-medium text-gray-700">Connection Key:</p>
                <div className="bg-gray-100 p-3 rounded-lg">
                  <p className="font-mono text-xs break-all select-all">{connectionKey}</p>
                </div>
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(connectionKey)
                    alert('Connection key copied to clipboard!')
                  }}
                  className="text-sm text-blue-600 hover:text-blue-800 underline"
                >
                  📋 Copy Key
                </button>
              </div>

              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mt-4">
                <p className="text-xs text-yellow-800">
                  <strong>💡 How to scan:</strong>
                </p>
                <ul className="text-xs text-yellow-700 mt-2 text-left list-disc list-inside space-y-1">
                  <li><strong>iOS:</strong> Scan with Camera app, then visit /qr-scanner on iPhone</li>
                  <li><strong>Desktop:</strong> Use phone camera or enter key manually</li>
                  <li><strong>Android:</strong> Use camera app to scan</li>
                  <li><strong>Or:</strong> Copy the connection key and paste it manually</li>
                </ul>
              </div>

              <div className="pt-4 border-t">
                <p className="text-xs text-gray-500">
                  This key is one-time use. Keep it secure!
                </p>
              </div>
            </div>

            <div className="mt-6 flex justify-end">
              <button
                onClick={() => {
                  setShowQRCodeModal(false)
                  setConnectionKey('')
                  setCreatedDeviceName('')
                }}
                className="px-6 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors font-medium"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )

  async function handleAction(deviceId, action) {
    if (!window.confirm(`Are you sure you want to ${action} this device?`)) {
      return
    }

    try {
      const token = localStorage.getItem('token')
      await axios.post(
        'http://localhost:5000/api/trigger_action',
        { device_id: deviceId, action },
        { headers: { Authorization: `Bearer ${token}` } }
      )
      alert(`${action} action triggered successfully!`)
      fetchDevices()
    } catch (error) {
      alert(error.response?.data?.error || 'Failed to trigger action')
    }
  }

  async function handleMarkMissing(deviceId) {
    if (!window.confirm('Mark this device as missing? This will activate tracking and capture screenshots.')) {
      return
    }

    try {
      const token = localStorage.getItem('token')
      await axios.post(
        'http://localhost:5000/api/mark_as_missing',
        { device_id: deviceId },
        { headers: { Authorization: `Bearer ${token}` } }
      )
      alert('Device marked as missing!')
      fetchDevices()
    } catch (error) {
      alert(error.response?.data?.error || 'Failed to mark device as missing')
    }
  }
}

export default Devices
